### ISSUE TITLE
App crash inside  androidx.media3.common.Format$Builder.build  method in Android/Amazon device OS version 5.1

### ISSUE THREAD

**Issue by rajneeshrawal** [androidx/media#1313]
### Version

Media3 1.3.1

### More version details

This issue is happening with media3 1.3.1. It is working fine with media3 1.2.1 version

### Devices that reproduce the issue

Android device OS version 5.1
Amazon Fire stick device 5.1.1

### Devices that do not reproduce the issue

Android Devices OS Version 6 and above

### Reproducible in the demo app?

Not tested

### Reproduction steps

Play any  DASH content on android OS version 5 or amazon fire stick verison 5.1.1.
 As per my understanding it is crashing because of "stream "  method call inside androidx.media3.common.Format class.   This method call is not supported in Android OS 5.1

### Expected result

Application should work fine on android devices OS version 5.1 

### Actual result

Fatal Exception: java.lang.NoSuchMethodError: No interface method stream()Ljava/util/stream/Stream; in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
       at androidx.media3.common.Format.<init>(Format.java:982)
       at androidx.media3.common.Format.<init>(Format.java:128)
       at androidx.media3.common.Format$Builder.build(Format.java:720)
       at androidx.media3.exoplayer.dash.DashMediaPeriod.buildPrimaryAndEmbeddedTrackGroupInfos(DashMediaPeriod.java:693)
       at androidx.media3.exoplayer.dash.DashMediaPeriod.buildTrackGroups(DashMediaPeriod.java:529)
       at androidx.media3.exoplayer.dash.DashMediaPeriod.<init>(DashMediaPeriod.java:160)
       at androidx.media3.exoplayer.dash.DashMediaSource.createPeriod(DashMediaSource.java:583)
       at androidx.media3.exoplayer.source.MergingMediaSource.createPeriod(MergingMediaSource.java:209)
       at androidx.media3.exoplayer.source.MaskingMediaPeriod.createPeriod(MaskingMediaPeriod.java:131)
       at androidx.media3.exoplayer.source.MaskingMediaSource.onChildSourceInfoRefreshed(MaskingMediaSource.java:213)
       at androidx.media3.exoplayer.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:154)
       at androidx.media3.exoplayer.source.WrappingMediaSource.onChildSourceInfoRefreshed(WrappingMediaSource.java:49)
       at androidx.media3.exoplayer.source.CompositeMediaSource.lambda$prepareChildSource$0(CompositeMediaSource.java:117)
       at androidx.media3.exoplayer.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:90)
       at androidx.media3.exoplayer.source.MergingMediaSource.onChildSourceInfoRefreshed(MergingMediaSource.java:281)
       at androidx.media3.exoplayer.source.MergingMediaSource.onChildSourceInfoRefreshed(MergingMediaSource.java:53)
       at androidx.media3.exoplayer.source.CompositeMediaSource.lambda$prepareChildSource$0(CompositeMediaSource.java:117)
       at androidx.media3.exoplayer.source.BaseMediaSource.refreshSourceInfo(BaseMediaSource.java:90)
       at androidx.media3.exoplayer.dash.DashMediaSource.processManifest(DashMediaSource.java:944)
       at androidx.media3.exoplayer.dash.DashMediaSource.onManifestLoadCompleted(DashMediaSource.java:722)
       at androidx.media3.exoplayer.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:1402)
       at androidx.media3.exoplayer.dash.DashMediaSource$ManifestCallback.onLoadCompleted(DashMediaSource.java:1397)
       at androidx.media3.exoplayer.upstream.Loader$LoadTask.handleMessage(Loader.java:487)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)

### Media

can be reproducible on any available public playback URL

### Bug Report

- [ ] You will email the zip file produced by `adb bugreport` to android-media-github@google.com after filing this issue.

**Comment by MGaetan89** [comment]
You can have a look at #1312 for pointers about how to fix the issue on your side

**Comment by menscikov** [comment]
I can confirm this crash. I see a lot of crashes in Firebase Crashlytics on Android 5 and Android 6 versions.

**Comment by tonihei** [comment]
Closing as a duplicate of #1312.
